Adding special aggregation and fixes for the ecs fore

diff --git a/aggregation/Makefile b/aggregation/Makefile
--- a/aggregation/Makefile
+++ b/aggregation/Makefile
@@ -8,6 +8,7 @@ GIT_COMMIT := $(shell git rev-parse --short HEAD)
 GIT_BRANCH_SANITIZED := $(subst /,-,${GIT_BRANCH})
 
 DOCKER_CONTAINER = encounterra-aggregation
+DOCKER_ECS_CONTAINER = encounterra-aggregation-ecs
 DOCKER_SANDBOX_REMOTE = ${ACCOUNT_NR}.dkr.ecr.eu-west-1.amazonaws.com
 
 docker.build:
@@ -39,6 +40,35 @@ docker.build:
 		echo "* short commit nr: ${GIT_COMMIT}"; \
 	fi
 
+docker.build_ecs:
+	@echo ""
+	@echo "Building ECS container..."
+	aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${DOCKER_SANDBOX_REMOTE}
+	docker build -t ${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED} --build-arg APP_VERSION=${GIT_COMMIT} --network host .
+	docker tag ${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED} ${DOCKER_ECS_CONTAINER}:latest
+	@if [ -z "${GIT_STATUS}" ]; then \
+        docker tag ${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED} ${DOCKER_ECS_CONTAINER}:${GIT_COMMIT}; \
+        docker tag ${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED} ${DOCKER_SANDBOX_REMOTE}/${DOCKER_ECS_CONTAINER}:${GIT_COMMIT}; \
+    fi
+	@echo ""
+	@echo "*"
+	@echo "*"
+	@echo "* Docker container built"
+	@echo "*"
+	@echo "*  tagged: ${FONT_BOLD}${DOCKER_ECS_CONTAINER}:latest${FONT_NORMAL}"
+	@echo "*  tagged: ${FONT_BOLD}${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED}${FONT_NORMAL}"
+	@if [ -z "${GIT_STATUS}" ]; then \
+		docker tag ${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED} ${DOCKER_ECS_CONTAINER}:${GIT_COMMIT}; \
+		docker tag ${DOCKER_ECS_CONTAINER}:${GIT_BRANCH_SANITIZED} ${DOCKER_SANDBOX_REMOTE}/${DOCKER_ECS_CONTAINER}:${GIT_COMMIT}; \
+	else \
+		echo "Workspace is dirty!"; \
+	fi
+	@echo "*"
+	@echo "*"
+	@if [ -z "${GIT_STATUS}" ]; then \
+		echo "* short commit nr: ${GIT_COMMIT}"; \
+	fi
+
 docker.push:
 	@echo ""
 	@echo "... pushing containers..."
@@ -56,6 +86,30 @@ docker.push:
 	@echo "* Container pushed"
 	@echo "*"
 	@echo "*  pushed: ${DOCKER_SANDBOX_REMOTE}/${DOCKER_CONTAINER}:${GIT_COMMIT}"
+	@echo "* "
+	@if [ -z "${GIT_STATUS}" ]; then \
+        echo "* short commit nr: ${GIT_COMMIT}"; \
+    fi
+	@echo "*"
+	@echo ""
+
+docker.push_ecs:
+	@echo ""
+	@echo "... pushing ECS containers..."
+	@echo ""
+	@if [ ! -z "${GIT_STATUS}" ]; then \
+        echo "Workspace is dirty, cannot push!"; \
+        echo ""; \
+        exit 1; \
+    fi
+	docker push ${DOCKER_SANDBOX_REMOTE}/${DOCKER_ECS_CONTAINER}:${GIT_COMMIT}
+
+	@echo ""
+	@echo "*"
+	@echo "*"
+	@echo "* Container pushed"
+	@echo "*"
+	@echo "*  pushed: ${DOCKER_SANDBOX_REMOTE}/${DOCKER_ECS_CONTAINER}:${GIT_COMMIT}"
 	@echo "* "
 	@if [ -z "${GIT_STATUS}" ]; then \
         echo "* short commit nr: ${GIT_COMMIT}"; \
